hotstrings["i'd"] := "I'd"
hotstrings["i'll"] := "I'll"
hotstrings["i'm"] := "I'm"
hotstrings["i've"] := "I've"

; hotstrings["id"] := "I'd"
hotstrings["il"] := "I'll"
hotstrings["im"] := "I'm"
hotstrings["iv"] := "I've"

hotstrings["u'd"] := "you'd"
hotstrings["u'll"] := "you'll"
hotstrings["u're"] := "you're"
hotstrings["u've"] := "you've"

hotstrings["ur"] := "your"
hotstrings["ud"] := "you'd"
hotstrings["ul"] := "you'll"
hotstrings["ure"] := "you're"
hotstrings["uv"] := "you've"
